import { BiBookOpen, BiBriefcase, BiBulb, BiCodeAlt } from "react-icons/bi";
import type { JobType } from "@/types";
import { formatDate } from "../../utils/date";

type TimelineItem = { title: string; organization: string; date: string; place: string; detail: string; icon: typeof BiBookOpen; tags: string[] };

export default function ExperienceTimeline({ jobs }: { jobs: JobType[] }) {
  const workItems: TimelineItem[] = jobs.map((job) => ({ title: job.jobTitle, organization: job.name, date: `${formatDate(job.startDate)} - ${job.endDate ? formatDate(job.endDate) : "Present"}`, place: "Professional experience", detail: job.description, icon: BiBriefcase, tags: ["Product thinking", "Teamwork"] }));
  const items: TimelineItem[] = [
    { title: "Information Technology studies", organization: "University / academic journey", date: "Ongoing", place: "Coursework and practical assignments", detail: "Building fundamentals across software engineering, database design, systems analysis, and the habits required to ship reliable work.", icon: BiBookOpen, tags: ["Database design", "Software engineering", "DFD modeling"] },
    { title: "Hands-on workshops and team projects", organization: "Practical learning", date: "Continuous", place: "Collaborative case studies", detail: "Learning by making: breaking down requirements, sharing implementation decisions, and turning case studies into working prototypes.", icon: BiBulb, tags: ["Team projects", "Case studies", "Problem solving"] },
    ...workItems,
    { title: "Independent full-stack practice", organization: "Personal lab", date: "Every week", place: "Open source and portfolio work", detail: "Exploring modern web architecture through production-minded experiments, APIs, CMS integrations, and thoughtful interface work.", icon: BiCodeAlt, tags: ["Next.js", "APIs", "TypeScript"] },
  ];

  return <section className="mt-24" aria-labelledby="timeline-heading"><div className="mb-10 max-w-2xl"><p className="eyebrow mb-3">The path so far</p><h2 id="timeline-heading" className="font-incognito text-4xl font-semibold tracking-[-0.05em] sm:text-5xl">Learning by building, building by learning.</h2><p className="mt-4 leading-relaxed text-zinc-500 dark:text-zinc-400">A timeline of the environments, assignments, and experiments shaping how I think about software.</p></div><ol className="relative ml-3 border-l border-indigo-500/20 pl-8 sm:ml-5 sm:pl-10">{items.map(({ title, organization, date, place, detail, icon: Icon, tags }) => <li key={`${title}-${organization}`} className="relative pb-10 last:pb-0"><span className="absolute -left-[3.05rem] grid h-9 w-9 place-items-center rounded-full border-4 border-[#f4f6fb] bg-indigo-500 text-lg text-white shadow-lg shadow-indigo-500/20 dark:border-[#09090b]"><Icon /></span><article className="glass rounded-[24px] p-5 sm:p-6"><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-start"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-indigo-500 dark:text-indigo-300">{date}</p><h3 className="mt-2 text-xl font-semibold tracking-tight">{title}</h3><p className="mt-1 text-sm font-semibold text-zinc-500 dark:text-zinc-400">{organization}</p></div><span className="text-xs text-zinc-400">{place}</span></div><p className="mt-4 max-w-2xl text-sm leading-relaxed text-zinc-500 dark:text-zinc-400">{detail}</p><div className="mt-5 flex flex-wrap gap-2">{tags.map((tag) => <span key={tag} className="rounded-full bg-black/[0.04] px-3 py-1 text-xs font-semibold text-zinc-500 dark:bg-white/[0.07] dark:text-zinc-300">{tag}</span>)}</div></article></li>)}</ol></section>;
}