"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect } from "react";
import { BiCodeAlt, BiLinkExternal, BiRightTopArrowCircle, BiX } from "react-icons/bi";
import type { ProjectType } from "@/types";
import { getProjectCategory, getProjectStack, getProjectStatus } from "./project-utils";

export default function ProjectModal({ project, onClose }: { project: ProjectType | null; onClose: () => void }) {
  useEffect(() => { if (!project) return; const handleKey = (event: KeyboardEvent) => event.key === "Escape" && onClose(); document.body.style.overflow = "hidden"; return () => { document.body.style.overflow = ""; window.removeEventListener("keydown", handleKey); }; }, [project, onClose]);
  if (!project) return null;
  return <div className="fixed inset-0 z-[70] flex justify-end bg-zinc-950/45 backdrop-blur-sm" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><aside role="dialog" aria-modal="true" aria-labelledby="project-modal-title" className="h-full w-full max-w-xl overflow-y-auto border-l border-white/[0.1] bg-[#f4f6fb] p-5 shadow-2xl dark:bg-[#101014] sm:p-8"><div className="flex items-center justify-between"><span className="eyebrow">Project brief</span><button type="button" onClick={onClose} className="tap-target grid place-items-center rounded-full border border-black/[0.08] text-xl text-zinc-500 dark:border-white/[0.1]" aria-label="Close project details"><BiX /></button></div>{project.coverImage?.image && <div className="relative mt-7 aspect-video overflow-hidden rounded-2xl"><Image src={project.coverImage.image} alt={project.coverImage.alt || project.name} fill sizes="(max-width: 640px) 100vw, 560px" className="object-cover" /></div>}<span className="mt-7 inline-flex rounded-full bg-indigo-500/10 px-3 py-1 text-[10px] font-bold uppercase tracking-[0.14em] text-indigo-600 dark:text-indigo-300">{getProjectStatus(project)} · {getProjectCategory(project)}</span><h2 id="project-modal-title" className="mt-3 font-incognito text-4xl font-semibold tracking-[-0.05em]">{project.name}</h2><p className="mt-4 text-base leading-relaxed text-zinc-500 dark:text-zinc-400">{project.tagline}</p><div className="mt-8 space-y-6"><div><h3 className="text-sm font-bold uppercase tracking-[0.14em]">Objective</h3><p className="mt-2 text-sm leading-relaxed text-zinc-500 dark:text-zinc-400">Turn a real workflow into a clearer, more reliable digital experience with a thoughtful interface and maintainable foundations.</p></div><div><h3 className="text-sm font-bold uppercase tracking-[0.14em]">Architecture notes</h3><p className="mt-2 text-sm leading-relaxed text-zinc-500 dark:text-zinc-400">The project is categorized as {getProjectCategory(project).toLowerCase()} work. Explore the full case study for the implementation details, decisions, and technical context.</p></div><div><h3 className="text-sm font-bold uppercase tracking-[0.14em]">Technical stack</h3><div className="mt-3 flex flex-wrap gap-2">{getProjectStack(project).map((tag) => <span key={tag} className="rounded-full border border-black/[0.08] px-3 py-1.5 text-xs font-semibold dark:border-white/[0.1]">{tag}</span>)}</div></div></div><div className="mt-9 flex flex-wrap gap-3"><Link href={`/projects/${project.slug}`} onClick={onClose} className="ios-button-primary flex-1">Full case study <BiRightTopArrowCircle /></Link>{project.projectUrl && <a href={project.projectUrl} target="_blank" rel="noreferrer" className="ios-button glass"><BiLinkExternal /> Live</a>}{project.repository && <a href={project.repository} target="_blank" rel="noreferrer" className="ios-button glass"><BiCodeAlt /> Source</a>}</div></aside></div>;
}