import Image from "next/image";
import Link from "next/link";
import { BiCodeAlt, BiInfoCircle, BiLinkExternal, BiRightTopArrowCircle } from "react-icons/bi";
import type { ProjectType } from "@/types";
import GlowCard from "../shared/GlowCard";
import { getProjectCategory, getProjectStack, getProjectStatus } from "./project-utils";

type ProjectCardProps = { project: ProjectType; index: number; onDetails: (project: ProjectType) => void };

export default function ProjectCard({ project, index, onDetails }: ProjectCardProps) {
  const stack = getProjectStack(project);
  return <GlowCard className="rounded-[28px]"><article className="glass group relative z-10 flex h-full flex-col overflow-hidden rounded-[28px]">
    <div className="relative aspect-[16/9] overflow-hidden bg-zinc-200 dark:bg-zinc-900">{project.coverImage?.image ? <Image src={project.coverImage.image} alt={project.coverImage.alt || project.name} fill sizes="(max-width: 768px) 100vw, (max-width: 1280px) 50vw, 33vw" className="object-cover transition duration-500 group-hover:scale-105" /> : <div className="grid h-full place-items-center bg-gradient-to-br from-indigo-500/20 to-teal-400/10 font-mono text-4xl text-indigo-500">0{index + 1}</div>}<div className="absolute inset-x-4 top-4 flex items-center justify-between"><span className="rounded-full border border-white/20 bg-black/40 px-3 py-1 text-[10px] font-bold uppercase tracking-[0.14em] text-white backdrop-blur-md">{getProjectStatus(project)}</span><span className="rounded-full border border-white/20 bg-black/40 px-3 py-1 text-[10px] font-bold uppercase tracking-[0.14em] text-white/80 backdrop-blur-md">0{index + 1}</span></div></div>
    <div className="flex flex-1 flex-col p-5"><p className="eyebrow text-[0.6rem]">{getProjectCategory(project)}</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.04em]">{project.name}</h2><p className="mt-2 min-h-[3rem] text-sm leading-relaxed text-zinc-500 dark:text-zinc-400">{project.tagline}</p><div className="mt-5 flex flex-wrap gap-2">{stack.map((tag) => <span key={tag} className="rounded-full bg-indigo-500/10 px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.1em] text-indigo-600 dark:text-indigo-300">{tag}</span>)}</div><div className="mt-auto flex flex-wrap gap-2 border-t border-black/[0.06] pt-5 dark:border-white/[0.08]"><Link href={`/projects/${project.slug}`} className="ios-button-primary flex-1">View case <BiRightTopArrowCircle /></Link><button type="button" onClick={() => onDetails(project)} className="tap-target grid place-items-center rounded-full border border-black/[0.08] text-lg text-zinc-500 transition hover:text-indigo-500 dark:border-white/[0.1]" aria-label={`View details for ${project.name}`}><BiInfoCircle /></button>{project.projectUrl && <a href={project.projectUrl} target="_blank" rel="noreferrer" className="tap-target grid place-items-center rounded-full border border-black/[0.08] text-lg text-zinc-500 transition hover:text-indigo-500 dark:border-white/[0.1]" aria-label={`Open ${project.name} live demo`}><BiLinkExternal /></a>}{project.repository && <a href={project.repository} target="_blank" rel="noreferrer" className="tap-target grid place-items-center rounded-full border border-black/[0.08] text-lg text-zinc-500 transition hover:text-indigo-500 dark:border-white/[0.1]" aria-label={`Open ${project.name} source code`}><BiCodeAlt /></a>}</div></div>
  </article></GlowCard>;
}